version: "3.9"
services:
  kong:
    image: kong:latest
    environment:
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_PG_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD_FILE
      - KONG_LUA_SSL_TRUSTED_CERTIFICATE=/etc/ssl/certs/ca-certificates.crt
      - KONG_DNS_STALE_TTL=120
      - KONG_DNS_VALID_TTL=30
      - KONG_DNS_ORDER=A,CNAME
      - KONG_DNS_NOT_FOUND_TTL=1
      - KONG_DNS_NO_SYNC=on
    secrets:
      - POSTGRES_PASSWORD_FILE
    env_file:
      - dev-db.env
    ports:
      - "80:8000"
      - "443:8443"
      - "8001:8001"
    working_dir: /tmp/run
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:8001/status" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    dns:
      - 1.1.1.1
      - 9.9.9.9
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - sample-ms
    command: kong start

  kong_migrations:
    image: kong:latest
    command: kong migrations bootstrap
    environment:
      - KONG_PG_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD_FILE
    secrets:
      - POSTGRES_PASSWORD_FILE
    env_file:
      - dev-db.env
    networks:
      - sample-ms
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

  kong_migrations_up:
    image: kong:latest
    command: kong migrations up && kong migrations finish
    environment:
      - KONG_PG_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD_FILE
    secrets:
      - POSTGRES_PASSWORD_FILE
    env_file:
      - dev-db.env
    networks:
      - sample-ms
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

  ms_sample_auth:
    image: ghcr.io/lukasa1993/ms-sample-auth:latest
    env_file:
      - node.env
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7702/health" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - sample-ms

  ms_sample_file:
    image: ghcr.io/lukasa1993/ms-sample-file:latest
    env_file:
      - ./node.env
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7702/health" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    secrets:
      - S3_KEY
      - S3_SECRET
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - sample-ms


  ms_sample_user:
    image: ghcr.io/lukasa1993/ms-sample-user:latest
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7702/health" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    secrets:
      - POSTGRES_PASSWORD_FILE
    env_file:
      - node.env
      - dev-db.env
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - sample-ms


  ms_sample_company:
    image: ghcr.io/lukasa1993/ms-sample-company:latest
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7702/health" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    secrets:
      - POSTGRES_PASSWORD_FILE
    env_file:
      - node.env
      - dev-db.env
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - sample-ms

  ms_sample_web_app:
    image: ghcr.io/lukasa1993/ms-sample-web-app:latest
    env_file:
      - ./node.env
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7702/health" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - sample-ms


  ms_sample_admin_web_app:
    image: ghcr.io/lukasa1993/ms-sample-admin-web-app:latest
    env_file:
      - ./node.env
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:7702/health" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any
    networks:
      - sample-ms



  sample_db:
    user: postgres
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      start_period: 5s
      timeout: 20s
      retries: 10
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - dev-db.env
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/POSTGRES_PASSWORD_FILE
    secrets:
      - POSTGRES_PASSWORD_FILE
    networks:
      - sample-ms


  sample_s3:
    image: minio/minio
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:9000/minio/health/live" ]
      start_period: 15s
      interval: 1m30s
      timeout: 10s
      retries: 3
    ports:
      - "9000:9000"
      - "40199:40199"
    volumes:
      - ./storage/minio:/data
    networks:
      - sample-ms
    secrets:
      - S3_KEY
      - S3_SECRET
    environment:
      MINIO_ROOT_USER_FILE: S3_KEY
      MINIO_ROOT_PASSWORD_FILE: S3_SECRET
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:40199 /data

networks:
  sample-ms:

secrets:
  POSTGRES_PASSWORD_FILE:
    file: ./postgress_password
  S3_KEY:
    file: ./s3_key
  S3_SECRET:
    file: ./s3_secret
